---
Name: open-semantic-search-config
---
Injector:
  SearchService:
    class: 'OpenSemanticSearch\Services\SolariumSearcher'
  IndexService:
    class: 'OpenSemanticSearch\Services\OSSIndexer'
  MetaDataService:
    class: 'OpenSemanticSearch\Services\MetaDataService'
    properties:
      searcher: %$SearchService
  IndexTask:
    class: 'OpenSemanticSearch\Models\IndexTask'
  MetaDataTask:
    class: 'OpenSemanticSearch\Models\MetaDataTask'
File:
  extensions:
    - 'OpenSemanticSearch\Extensions\MetaDataExtension'
#    - 'OpenSemanticSearch\Extensions\FileExtension'              # add in site config for 'normal' files
#    - 'OpenSemanticSearch\Extensions\VersionedModelExtension'     # add in site config for 'versioned' files
Page:
  extensions:
    - 'OpenSemanticSearch\Extensions\MetaDataExtension'
#    - 'OpenSemanticSearch\Extensions\PageExtension'              # add in app config to Page or subclasses to make searchable
OpenSemantionSearch\Models\IndexedURL:
  extensions:
    - 'Modular\Fields\Title'
    - 'Modular\Fields\Description'
OpenSemanticSearch\Models\IndexTask:
  dependencies:
    service: %$IndexService
  extensions:
    - 'OpenSemanticSearch\Fields\IndexAction'
    - 'OpenSemanticSearch\Fields\IndexedItem'
OpenSemanticSearch\Models\MetaDataTask:
  dependencies:
    service: %$MetaDataService
  extensions:
    - 'OpenSemanticSearch\Fields\IndexedItem'

# add the following in app config for files
# File:
#  extensions:
#    - OpenSemanticSearch\Extensions\FileExtension
#
# add the following in app config for Versioned files
# File:
#  extensions:
#    - OpenSemanticSearch\Extensions\VersionedFileExtension
#
# add the following in app config for each Page class you want to make searchable (or Page for all pages)
# Page:
#  extensions:
#    - OpenSemanticSearch\Extensions\PageExtension
#
OpenSemanticSearch\Services\Service:
  path_map:
    dev:
      '/assets/': '/mount/files/assets/'
  core:
    dev: 'core1'
OpenSemanticSearch\Services\OSSIndexer:
  context_options:
    dev:
      oss:
        http:
          method: 'GET'
          timeout: 20
  endpoints:
    dev:
      oss:
        '*': 'http://localhost:9010/search-apps/api/{endpoint}'
OpenSemanticSearch\Services\SolrSearcher:
  endpoints:
    dev:
      solr:
        '*': 'http://localhost:9011/solr'
