---
Name: open-semantic-search-config
---
Injector:
  SearchService:
    class: 'OpenSemanticSearch\Services\Search'
  IndexService:
    class: 'OpenSemanticSearch\Services\Index'
  MetaDataService:
    class: 'OpenSemanticSearch\Services\MetaDataService'
    properties:
      searcher: %$SearchService
  IndexTask:
    class: 'OpenSemanticSearch\Models\Index'
  MetaDataTask:
    class: 'OpenSemanticSearch\Models\MetaData'
File:
  extensions:
    - 'Modular\Fields\FileContentHash'
    - 'Modular\Fields\FileModifiedStamp'
    - 'OpenSemanticSearch\Extensions\MetaDataExtension'
    - 'Modular\Extensions\Model\TrackedValue("Filename")'

#    - 'OpenSemanticSearch\Extensions\FileExtension'              # add in site config for 'normal' files
#    - 'OpenSemanticSearch\Extensions\VersionedModelExtension'     # add in site config for 'versioned' files
Page:
  extensions:
    - 'OpenSemanticSearch\Extensions\MetaDataExtension'

#    - 'OpenSemanticSearch\Extensions\PageExtension'              # add in app config to Page or subclasses to make searchable
OpenSemantionSearch\Models\IndexedURL:
  extensions:
    - 'Modular\Fields\Title'
    - 'Modular\Fields\Description'
    - 'Modular\Fields\URL'
OpenSemanticSearch\Tasks\Index:
  dependencies:
    service: %$IndexService
  extensions:
    - 'OpenSemanticSearch\Fields\IndexAction'
    - 'OpenSemanticSearch\Fields\IndexedItem'
OpenSemanticSearch\Tasks\MetaData:
  dependencies:
    service: %$MetaDataService
  extensions:
    - 'OpenSemanticSearch\Fields\IndexedItem'
    - 'OpenSemanticSearch\Fields\SourceQuery'

# add the following in app config for files
# File:
#  extensions:
#    - OpenSemanticSearch\Extensions\FileExtension
#
# add the following in app config for Versioned files
# File:
#  extensions:
#    - OpenSemanticSearch\Extensions\VersionedFileExtension
#
# add the following in app config for each Page class you want to make searchable (or Page for all pages)
# Page:
#  extensions:
#    - OpenSemanticSearch\Extensions\PageExtension
#
OpenSemanticSearch\Services\Service:
  path_map:
    dev:
      '/assets/': '/mount/files/assets/'
  core:
    '*': 'core1'

# these lines should be configured in site config to point to your opensemanticsearch services, they default to
# localhost for development environment, also add test and live environments the same format as from 'dev' key down
OpenSemanticSearch\Services\OSSIndexer:
  endpoints:
    dev:
      oss:
        '*': 'http://localhost:9010/search-apps/api/{endpoint}'
OpenSemanticSearch\Services\SolrSearcher:
  endpoints:
    dev:
      solr:
        '*': 'http://localhost:9011/solr'
