---
Name: open-semantic-search-config
---
Injector:
  SearchService:
    class: 'OpenSemanticSearch\Services\SolariumSearcher'
  IndexService:
    class: 'OpenSemanticSearch\Services\OSSIndexer'
  MetaDataService:
    class: 'OpenSemanticSearch\Services\MetaDataService'
    properties:
      searcher: %$SearchService
  IndexTask:
    class: 'OpenSemanticSearch\Models\IndexTask'
  MetaDataTask:
    class: 'OpenSemanticSearch\Models\MetaDataTask'
OpenSemanticSearch\Models\IndexTask:
  dependencies:
    service: %$IndexService
OpenSemanticSearch\Models\MetaDataTask:
  dependencies:
    service: %$MetaDataService
OpenSemanticSearch\Services\Service:
  path_map:
    dev:
      '/assets/': '/mount/files/assets/'
  core:
    '*': 'core1'

# these lines should be configured in site config to point to your opensemanticsearch services, they default to
# localhost for development environment, also add test and live environments the same format as from 'dev' key down
OpenSemanticSearch\Services\OSSIndexer:
  endpoints:
    dev:
      oss:
        '*': 'http://localhost:9010/search-apps/api/{endpoint}'
OpenSemanticSearch\Services\SolrSearcher:
  endpoints:
    dev:
      solr:
        '*': 'http://localhost:9011/solr'
