---
Name: open-semantic-search-config
---
Injector:
  SearchService:
    class: 'OpenSemanticSearch\Services\Search'
  IndexTask:
    class: 'OpenSemanticSearch\Tasks\Index'
  IndexService:
    class: 'OpenSemanticSearch\Services\Index'
  MetaDataTask:
    class: 'OpenSemanticSearch\Tasks\MetaData'
  MetaDataService:
    class: 'OpenSemanticSearch\Services\MetaData'
    properties:
      searcher: %$SearchService
OpenSemanticSearch\Tasks\Index:
  dependencies:
    service: %$IndexService
OpenSemanticSearch\Tasks\MetaData:
  dependencies:
    service: %$MetaDataService
OpenSemanticSearch\Services\Service:
  path_map:
    dev:
      '/assets/': '/mount/files/assets/'
  core:
    '*': 'core1'
OpenSemanticSearch\Services\Index:
  endpoints:
    dev:
      oss:
        '*': 'http://localhost:9010/search-apps/api/{endpoint}'
OpenSemanticSearch\Services\Search:
  endpoints:
    dev:
      solr:
        '*': 'http://localhost:9011/solr'
